import { BlockInstanceConfig } from './template.types';

/**
 * INSTÂNCIAS DE BLOCOS — Gerado por ai-bootstrap-meta
 */
export const UI_BLOCK_INSTANCES: BlockInstanceConfig[] = [
  {
    instanceId: 'dados-solicitante-analise-rh',
    blockId: 'dados-solicitante',
    hostType: 'page',
    hostId: 'analise-rh',
    selector: 'app-dados-solicitante',
    templateFile: 'src/app/modules/analise-rh/analise-rh.component.html',
    dataAttribute: 'dados-solicitante-analise-rh',
    optional: false,
  },
  {
    instanceId: 'dados-gestor-analise-rh',
    blockId: 'dados-gestor',
    hostType: 'page',
    hostId: 'analise-rh',
    selector: 'app-dados-gestor',
    templateFile: 'src/app/modules/analise-rh/analise-rh.component.html',
    dataAttribute: 'dados-gestor-analise-rh',
    optional: true,
  },
  {
    instanceId: 'dados-solicitacao-analise-rh',
    blockId: 'dados-solicitacao',
    hostType: 'page',
    hostId: 'analise-rh',
    selector: 'app-dados-solicitacao',
    templateFile: 'src/app/modules/analise-rh/analise-rh.component.html',
    dataAttribute: 'dados-solicitacao-analise-rh',
    optional: false,
  },
  {
    instanceId: 'observacao-analise-rh',
    blockId: 'observacao',
    hostType: 'page',
    hostId: 'analise-rh',
    selector: 'app-observacao',
    templateFile: 'src/app/modules/analise-rh/analise-rh.component.html',
    dataAttribute: 'observacao-analise-rh',
    optional: false,
  },
  {
    instanceId: 'dados-solicitante-detalhes',
    blockId: 'dados-solicitante',
    hostType: 'page',
    hostId: 'detalhes',
    selector: 'app-dados-solicitante',
    templateFile: 'src/app/modules/detalhes/detalhes.component.html',
    dataAttribute: 'dados-solicitante-detalhes',
    optional: false,
  },
  {
    instanceId: 'dados-gestor-detalhes',
    blockId: 'dados-gestor',
    hostType: 'page',
    hostId: 'detalhes',
    selector: 'app-dados-gestor',
    templateFile: 'src/app/modules/detalhes/detalhes.component.html',
    dataAttribute: 'dados-gestor-detalhes',
    optional: true,
  },
  {
    instanceId: 'dados-solicitante-revisao',
    blockId: 'dados-solicitante',
    hostType: 'page',
    hostId: 'revisao',
    selector: 'app-dados-solicitante',
    templateFile: 'src/app/modules/revisao/revisao.component.html',
    dataAttribute: 'dados-solicitante-revisao',
    optional: false,
  },
  {
    instanceId: 'dados-gestor-revisao',
    blockId: 'dados-gestor',
    hostType: 'page',
    hostId: 'revisao',
    selector: 'app-dados-gestor',
    templateFile: 'src/app/modules/revisao/revisao.component.html',
    dataAttribute: 'dados-gestor-revisao',
    optional: true,
  },
  {
    instanceId: 'dados-solicitacao-revisao',
    blockId: 'dados-solicitacao',
    hostType: 'page',
    hostId: 'revisao',
    selector: 'app-dados-solicitacao',
    templateFile: 'src/app/modules/revisao/revisao.component.html',
    dataAttribute: 'dados-solicitacao-revisao',
    optional: false,
  },
  {
    instanceId: 'observacao-revisao',
    blockId: 'observacao',
    hostType: 'page',
    hostId: 'revisao',
    selector: 'app-observacao',
    templateFile: 'src/app/modules/revisao/revisao.component.html',
    dataAttribute: 'observacao-revisao',
    optional: false,
  },
  {
    instanceId: 'dados-solicitante-solicitacao',
    blockId: 'dados-solicitante',
    hostType: 'page',
    hostId: 'solicitacao',
    selector: 'app-dados-solicitante',
    templateFile: 'src/app/modules/solicitacao/solicitacao.component.html',
    dataAttribute: 'dados-solicitante-solicitacao',
    optional: false,
  },
  {
    instanceId: 'dados-gestor-solicitacao',
    blockId: 'dados-gestor',
    hostType: 'page',
    hostId: 'solicitacao',
    selector: 'app-dados-gestor',
    templateFile: 'src/app/modules/solicitacao/solicitacao.component.html',
    dataAttribute: 'dados-gestor-solicitacao',
    optional: true,
  },
  {
    instanceId: 'dados-solicitacao-solicitacao',
    blockId: 'dados-solicitacao',
    hostType: 'page',
    hostId: 'solicitacao',
    selector: 'app-dados-solicitacao',
    templateFile: 'src/app/modules/solicitacao/solicitacao.component.html',
    dataAttribute: 'dados-solicitacao-solicitacao',
    optional: false,
  },
  {
    instanceId: 'dados-dependentes-table',
    blockId: 'dados-dependentes',
    hostType: 'block',
    hostId: 'dados-dependentes',
    selector: 'hst-selectable-table',
    templateFile: 'src/app/shared/components/dados-dependentes/dados-dependentes.component.html',
    dataAttribute: 'dados-dependentes-table',
    optional: false,
  },
];
